# 如果您的站点使用 'https'，确保您的 baseURL 不是用 'http' 写的，否则您的站点地图会包含 http URL
baseURL: https://mczeno.github.io
title: Mczeno's Site
languageCode: "zh-cn"
defaultContentLanguage: "zh"
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 10

languages:
  zh:
    languageName: "中文"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: 归档
          url: archives
          weight: 5
        - name: 搜索
          url: search/
          weight: 10
        - name: 标签
          url: tags/
          weight: 15

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Mczeno的个人博客"
  author: Mczeno

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true

  homeInfoParams:
    Title: "欢迎来到我的博客"
    Content: >
      这里是 Mczeno 的个人博客，分享技术、学习心得和生活感悟。

  # 如果需要社交链接，可以取消注释并修改
  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/mczeno"

  # 编辑文章链接配置
  # editPost:
  #   URL: "https://github.com/yourusername/yourrepo/tree/main/content"
  #   Text: "建议修改"
  #   appendFilePath: true

  assets:
    disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
